northwind:
  outputs:
    dev:
      dataset: dbt_cosmos_airflow
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/include/learning-gcp-369416-93c90510f16c.json
      location: US
      method: service-account
      priority: interactive
      project: learning-gcp-369416
      threads: 1
      type: bigquery
  target: dev